### ISSUE TITLE
Need help to start

### ISSUE THREAD

**Issue by xBlizZer** [EricSmekens/node-serial-obd#14]
Got this issue:

`pi@raspberrypi:~/project/node-serial-obd/example $ node test.js
/home/pi/project/node-serial-obd/lib/obd.js:155
    this.serial = new SerialPort(this.SERIAL_PORT, this.OPTIONS);
                  ^

TypeError: SerialPort is not a constructor
    at OBDReader.connect (/home/pi/project/node-serial-obd/lib/obd.js:155:19)
    at Object.<anonymous> (/home/pi/project/node-serial-obd/example/test.js:46:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
`

need help

**Comment by EricSmekens** [comment]
Can you check which version of serialport was downloaded? (In package-lock.json).

**Comment by xBlizZer** [comment]
It is  `  "name": "cardash",
  "private": true,
  "dependencies": {
    "async": "^0.9.0",
    "bluetooth-serial-port": "^1.1.4",
    "express": "^4.9.5",
    "serialport": "^1.4.6",
    "socket.io": "^1.1.0"`

**Comment by EricSmekens** [comment]
Release 0.2.2 package, let me know if this solves your problem.

(It was using a new version of serialport, so I fixed that problem in 0.2.2, and I also updated the example code).

**Comment by xBlizZer** [comment]
i@raspberrypi:~/Desktop/Cardash-master $ node example/test.js
Serial port [COM4] is not ready
It might work now if I connect my bluetooth adapter thanks!
